import { ApiError, UploadAbortedError, type ApiClient } from "./client";
import { DEMO_IDS } from "./demo";
import type {
  AnalysisList,
  AnalysisResult,
  AnalysisStatus,
  AnalysisSummary,
  FramesPayload,
} from "./types";

/**
 * Backend stand-in for VITE_USE_MOCKS=true. Serves real pipeline output from
 * /public/mock (generated by scripts/make_mock_fixtures.py) and simulates
 * uploads and the worker's stage progression for newly created analyses.
 * A file whose name contains "fail" fails with NO_PERSON_DETECTED.
 */

const TEMPLATE_ID = "demo-serve-1";

export const MOCK_STAGES: { status: AnalysisStatus; ms: number }[] = [
  { status: "queued", ms: 1000 },
  { status: "extracting_pose", ms: 3000 },
  { status: "analyzing", ms: 1000 },
  { status: "rendering", ms: 1500 },
];

interface Created {
  summary: AnalysisSummary;
  startedAt: number | null;
  failing: boolean;
}

export interface MockOptions {
  now?: () => number;
  latencyMs?: number;
  fetchJson?: <T>(path: string) => Promise<T>;
}

async function defaultFetchJson<T>(path: string): Promise<T> {
  const res = await fetch(path);
  if (!res.ok) throw new ApiError(res.status, `Mock fixture ${path} not found`);
  return (await res.json()) as T;
}

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

export function createMockClient(options: MockOptions = {}): ApiClient {
  const now = options.now ?? Date.now;
  const latency = options.latencyMs ?? 250;
  const fetchJson = options.fetchJson ?? defaultFetchJson;
  const created = new Map<string, Created>();
  let counter = 0;

  const delay = () => (latency > 0 ? sleep(latency) : Promise.resolve());

  function isDemo(id: string): boolean {
    return (DEMO_IDS as readonly string[]).includes(id);
  }

  function current(entry: Created): AnalysisSummary {
    const { summary, startedAt, failing } = entry;
    if (startedAt === null || summary.status === "failed" || summary.status === "succeeded") {
      return summary;
    }
    let elapsed = now() - startedAt;
    for (const stage of MOCK_STAGES) {
      if (elapsed < stage.ms) return { ...summary, status: stage.status };
      if (failing && stage.status === "extracting_pose") {
        entry.summary = {
          ...summary,
          status: "failed",
          error: {
            code: "NO_PERSON_DETECTED",
            message: "We couldn't detect a person clearly. Check the filming guide.",
          },
        };
        return entry.summary;
      }
      elapsed -= stage.ms;
    }
    entry.summary = {
      ...summary,
      status: "succeeded",
      thumbnail_url: `/mock/${TEMPLATE_ID}/thumbnail.jpg`,
      counts: { good: 3, borderline: 2, off: 0, unknown: 5 },
    };
    return entry.summary;
  }

  function entryOrThrow(id: string): Created {
    const entry = created.get(id);
    if (!entry) throw new ApiError(404, "Analysis not found");
    return entry;
  }

  function assertSucceeded(id: string): void {
    if (isDemo(id)) return;
    const status = current(entryOrThrow(id)).status;
    if (status !== "succeeded") throw new ApiError(409, `Analysis is ${status}`);
  }

  return {
    async createAnalysis(body) {
      await delay();
      counter += 1;
      const id = `mock-${counter}`;
      const ts = new Date(now()).toISOString();
      const summary: AnalysisSummary = {
        id,
        hand: body.hand,
        status: "awaiting_upload",
        filename: body.filename,
        created_at: ts,
        updated_at: ts,
        error: null,
        thumbnail_url: null,
        counts: null,
      };
      created.set(id, { summary, startedAt: null, failing: /fail/i.test(body.filename) });
      return {
        analysis: summary,
        upload: {
          url: `mock://upload/${id}`,
          method: "PUT",
          headers: { "Content-Type": body.content_type },
          expires_at: new Date(now() + 15 * 60_000).toISOString(),
        },
      };
    },

    async uploadVideo(_target, file, onProgress, signal) {
      const steps = 20;
      const totalMs = Math.min(3000, 800 + file.size / 50_000);
      for (let i = 1; i <= steps; i++) {
        if (signal?.aborted) throw new UploadAbortedError();
        await sleep(totalMs / steps);
        onProgress(i / steps);
      }
    },

    async startAnalysis(id) {
      await delay();
      const entry = entryOrThrow(id);
      if (entry.summary.status !== "awaiting_upload") {
        throw new ApiError(409, `Analysis is already ${entry.summary.status}`);
      }
      entry.startedAt = now();
      entry.summary = { ...entry.summary, status: "queued" };
      return current(entry);
    },

    async retryAnalysis(id) {
      await delay();
      const entry = entryOrThrow(id);
      if (current(entry).status !== "failed") {
        throw new ApiError(409, "Only failed analyses can be retried");
      }
      entry.failing = false;
      entry.startedAt = now();
      entry.summary = { ...entry.summary, status: "queued", error: null };
      return current(entry);
    },

    async getAnalysis(id) {
      await delay();
      if (isDemo(id)) return fetchJson<AnalysisSummary>(`/mock/${id}/summary.json`);
      return current(entryOrThrow(id));
    },

    async listAnalyses() {
      await delay();
      const fixtures = await fetchJson<AnalysisList>("/mock/analyses.json");
      const mine = [...created.values()].map(current).reverse();
      return { items: [...mine, ...fixtures.items], next_cursor: null };
    },

    async getResult(id) {
      await delay();
      assertSucceeded(id);
      const result = await fetchJson<AnalysisResult>(
        `/mock/${isDemo(id) ? id : TEMPLATE_ID}/result.json`,
      );
      return { ...result, id };
    },

    async getFrames(id) {
      await delay();
      assertSucceeded(id);
      return fetchJson<FramesPayload>(`/mock/${isDemo(id) ? id : TEMPLATE_ID}/frames.json`);
    },
  };
}
