/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Signup
         * @description Create an account, sign in, and email a link to confirm the address.
         */
        post: operations["signup_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description End the current session. Succeeds even if not signed in.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        /**
         * Delete Account
         * @description Permanently delete the account and every video and analysis in it.
         */
        delete: operations["delete_account_auth_me_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Email
         * @description Confirm an address from the emailed link. Works without signing in, since the
         *     link may be opened on another device.
         */
        post: operations["verify_email_auth_verify_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resend Verification
         * @description Email a fresh confirmation link. Earlier links stop working.
         */
        post: operations["resend_verification_auth_verify_email_resend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Password Reset
         * @description Email a reset link if the address has an account. The response is the same
         *     either way, so it can't be used to find out who has an account.
         */
        post: operations["request_password_reset_auth_password_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Password Reset
         * @description Set a new password from the emailed link. Signs out every device, this one included.
         */
        post: operations["confirm_password_reset_auth_password_reset_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Analyses */
        get: operations["list_analyses_analyses_get"];
        put?: never;
        /**
         * Create Analysis
         * @description Create a record and return a presigned URL to PUT the video to.
         */
        post: operations["create_analysis_analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyses/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analysis */
        get: operations["get_analysis_analyses__analysis_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Analysis
         * @description Delete an analysis with its video and results, whatever its status.
         *
         *     If a worker is processing it, the worker finds the job gone and stops: its
         *     status writes no longer match a row, and anything it publishes is removed.
         */
        delete: operations["delete_analysis_analyses__analysis_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyses/{analysis_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Analysis
         * @description Queue the analysis once the upload has finished.
         */
        post: operations["start_analysis_analyses__analysis_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyses/{analysis_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Analysis */
        post: operations["retry_analysis_analyses__analysis_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyses/{analysis_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Result */
        get: operations["get_result_analyses__analysis_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyses/{analysis_id}/frames": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Frames
         * @description Per-frame landmarks and metric series.
         *
         *     Served straight from the pipeline's frames.json (validated against
         *     FramesPayload in tests) to avoid re-parsing a large payload per request.
         */
        get: operations["get_frames_analyses__analysis_id__frames_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisList */
        AnalysisList: {
            /** Items */
            items: components["schemas"]["AnalysisSummary"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** AnalysisResult */
        AnalysisResult: {
            /** Id */
            id: string;
            /**
             * Hand
             * @enum {string}
             */
            hand: "right" | "left";
            /** Fps */
            fps: number;
            /** N Frames */
            n_frames: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
            phases: components["schemas"]["PhaseFrames"];
            metrics: components["schemas"]["PhaseMetrics"];
            labels: components["schemas"]["PhaseLabels"];
            ranges: components["schemas"]["PhaseRanges"];
            /** Feedback */
            feedback: components["schemas"]["FeedbackItem"][];
            /** Warnings */
            warnings: string[];
            /** Video Url */
            video_url: string;
            /** Annotated Video Url */
            annotated_video_url?: string | null;
            /** Thumbnail Url */
            thumbnail_url?: string | null;
        };
        /** AnalysisSummary */
        AnalysisSummary: {
            /** Id */
            id: string;
            /**
             * Hand
             * @enum {string}
             */
            hand: "right" | "left";
            /**
             * Status
             * @enum {string}
             */
            status: "awaiting_upload" | "queued" | "extracting_pose" | "analyzing" | "rendering" | "succeeded" | "failed";
            /** Filename */
            filename: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            error?: components["schemas"]["ApiError"] | null;
            /** Thumbnail Url */
            thumbnail_url?: string | null;
            counts?: components["schemas"]["StatusCounts"] | null;
        };
        /** ApiError */
        ApiError: {
            /**
             * Code
             * @enum {string}
             */
            code: "UNREADABLE_VIDEO" | "VIDEO_TOO_LONG" | "FPS_TOO_LOW" | "NO_PERSON_DETECTED" | "NOT_A_SERVE" | "INTERNAL";
            /** Message */
            message: string;
        };
        /** CreateAnalysisRequest */
        CreateAnalysisRequest: {
            /**
             * Hand
             * @enum {string}
             */
            hand: "right" | "left";
            /** Filename */
            filename: string;
            /**
             * Content Type
             * @enum {string}
             */
            content_type: "video/mp4" | "video/quicktime";
            /** Size Bytes */
            size_bytes: number;
        };
        /** CreateAnalysisResponse */
        CreateAnalysisResponse: {
            analysis: components["schemas"]["AnalysisSummary"];
            upload: components["schemas"]["UploadTarget"];
        };
        /**
         * DeleteAccountRequest
         * @description The current password, so a borrowed or stolen session can't delete the account.
         */
        DeleteAccountRequest: {
            /** Password */
            password: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Detail */
            detail: string;
        };
        /** FeedbackItem */
        FeedbackItem: {
            /** Text */
            text: string;
            /** Phase */
            phase?: ("trophy" | "racket_drop" | "contact") | null;
            /** Metric */
            metric?: ("front_knee_flexion" | "back_knee_flexion" | "elbow_angle" | "trunk_tilt" | "wrist_height") | null;
            /** Status */
            status?: ("good" | "borderline" | "off" | "unknown") | null;
        };
        /** FrameLandmarks */
        FrameLandmarks: {
            raw: components["schemas"]["RawLandmarks"];
            smoothed: components["schemas"]["SmoothedLandmarks"];
        };
        /** FramesPayload */
        FramesPayload: {
            /** Fps */
            fps: number;
            /** N Frames */
            n_frames: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
            phases: components["schemas"]["PhaseFrames"];
            landmarks: components["schemas"]["FrameLandmarks"];
            series: components["schemas"]["MetricSeries"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LandmarkTrack
         * @description Normalised coordinates (0-1 of the frame), one entry per frame; null when missing.
         */
        LandmarkTrack: {
            /** X */
            x: (number | null)[];
            /** Y */
            y: (number | null)[];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MetricLabels */
        MetricLabels: {
            /** Front Knee Flexion */
            front_knee_flexion?: ("good" | "borderline" | "off" | "unknown") | null;
            /** Back Knee Flexion */
            back_knee_flexion?: ("good" | "borderline" | "off" | "unknown") | null;
            /** Elbow Angle */
            elbow_angle?: ("good" | "borderline" | "off" | "unknown") | null;
            /** Trunk Tilt */
            trunk_tilt?: ("good" | "borderline" | "off" | "unknown") | null;
            /** Wrist Height */
            wrist_height?: ("good" | "borderline" | "off" | "unknown") | null;
        };
        /** MetricRange */
        MetricRange: {
            /** Good */
            good: [
                number,
                number
            ];
            /** Borderline */
            borderline: [
                number,
                number
            ];
        };
        /** MetricRanges */
        MetricRanges: {
            front_knee_flexion?: components["schemas"]["MetricRange"] | null;
            back_knee_flexion?: components["schemas"]["MetricRange"] | null;
            elbow_angle?: components["schemas"]["MetricRange"] | null;
            trunk_tilt?: components["schemas"]["MetricRange"] | null;
            wrist_height?: components["schemas"]["MetricRange"] | null;
        };
        /** MetricSeries */
        MetricSeries: {
            /** Front Knee Flexion */
            front_knee_flexion: (number | null)[];
            /** Back Knee Flexion */
            back_knee_flexion: (number | null)[];
            /** Elbow Angle */
            elbow_angle: (number | null)[];
            /** Trunk Tilt */
            trunk_tilt: (number | null)[];
            /** Wrist Height */
            wrist_height: (number | null)[];
        };
        /** MetricValues */
        MetricValues: {
            /** Front Knee Flexion */
            front_knee_flexion: number | null;
            /** Back Knee Flexion */
            back_knee_flexion: number | null;
            /** Elbow Angle */
            elbow_angle: number | null;
            /** Trunk Tilt */
            trunk_tilt: number | null;
            /** Wrist Height */
            wrist_height: number | null;
        };
        /** PasswordResetConfirm */
        PasswordResetConfirm: {
            /** Token */
            token: string;
            /** Password */
            password: string;
        };
        /** PasswordResetRequest */
        PasswordResetRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** PhaseFrames */
        PhaseFrames: {
            /** Trophy */
            trophy: number | null;
            /** Racket Drop */
            racket_drop: number | null;
            /** Contact */
            contact: number | null;
        };
        /** PhaseLabels */
        PhaseLabels: {
            trophy: components["schemas"]["MetricLabels"];
            racket_drop: components["schemas"]["MetricLabels"];
            contact: components["schemas"]["MetricLabels"];
        };
        /** PhaseMetrics */
        PhaseMetrics: {
            trophy: components["schemas"]["MetricValues"];
            racket_drop: components["schemas"]["MetricValues"];
            contact: components["schemas"]["MetricValues"];
        };
        /** PhaseRanges */
        PhaseRanges: {
            trophy: components["schemas"]["MetricRanges"];
            racket_drop: components["schemas"]["MetricRanges"];
            contact: components["schemas"]["MetricRanges"];
        };
        /** RawLandmarkTrack */
        RawLandmarkTrack: {
            /** X */
            x: (number | null)[];
            /** Y */
            y: (number | null)[];
            /** V */
            v: (number | null)[];
        };
        /** RawLandmarks */
        RawLandmarks: {
            nose: components["schemas"]["RawLandmarkTrack"];
            left_shoulder: components["schemas"]["RawLandmarkTrack"];
            right_shoulder: components["schemas"]["RawLandmarkTrack"];
            left_elbow: components["schemas"]["RawLandmarkTrack"];
            right_elbow: components["schemas"]["RawLandmarkTrack"];
            left_wrist: components["schemas"]["RawLandmarkTrack"];
            right_wrist: components["schemas"]["RawLandmarkTrack"];
            left_hip: components["schemas"]["RawLandmarkTrack"];
            right_hip: components["schemas"]["RawLandmarkTrack"];
            left_knee: components["schemas"]["RawLandmarkTrack"];
            right_knee: components["schemas"]["RawLandmarkTrack"];
            left_ankle: components["schemas"]["RawLandmarkTrack"];
            right_ankle: components["schemas"]["RawLandmarkTrack"];
        };
        /** SignupRequest */
        SignupRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** SmoothedLandmarks */
        SmoothedLandmarks: {
            nose: components["schemas"]["LandmarkTrack"];
            left_shoulder: components["schemas"]["LandmarkTrack"];
            right_shoulder: components["schemas"]["LandmarkTrack"];
            left_elbow: components["schemas"]["LandmarkTrack"];
            right_elbow: components["schemas"]["LandmarkTrack"];
            left_wrist: components["schemas"]["LandmarkTrack"];
            right_wrist: components["schemas"]["LandmarkTrack"];
            left_hip: components["schemas"]["LandmarkTrack"];
            right_hip: components["schemas"]["LandmarkTrack"];
            left_knee: components["schemas"]["LandmarkTrack"];
            right_knee: components["schemas"]["LandmarkTrack"];
            left_ankle: components["schemas"]["LandmarkTrack"];
            right_ankle: components["schemas"]["LandmarkTrack"];
        };
        /** StatusCounts */
        StatusCounts: {
            /** Good */
            good: number;
            /** Borderline */
            borderline: number;
            /** Off */
            off: number;
            /** Unknown */
            unknown: number;
        };
        /** UploadTarget */
        UploadTarget: {
            /** Url */
            url: string;
            /**
             * Method
             * @default PUT
             * @constant
             */
            method: "PUT";
            /** Headers */
            headers: {
                [key: string]: string;
            };
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** User */
        User: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Email Verified
             * @default false
             */
            email_verified: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifyEmailRequest */
        VerifyEmailRequest: {
            /** Token */
            token: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    signup_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_account_auth_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteAccountRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    verify_email_auth_verify_email_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resend_verification_auth_verify_email_resend_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    request_password_reset_auth_password_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    confirm_password_reset_auth_password_reset_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirm"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_analyses_analyses_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisList"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_analysis_analyses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateAnalysisResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_analysis_analyses__analysis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisSummary"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_analysis_analyses__analysis_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_analysis_analyses__analysis_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisSummary"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    retry_analysis_analyses__analysis_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisSummary"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_result_analyses__analysis_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResult"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_frames_analyses__analysis_id__frames_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FramesPayload"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
